#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# quota-hard-block.sh — enforce the backup-link quota at packet level
#
# Once the quota snapshot reports QUOTA_HARD_BLOCK_PCT or more, an nftables
# table drops every packet leaving through BACKUP_IFACE, except to the
# destinations in QUOTA_HARD_BLOCK_ALLOW (typically the modem's own subnet,
# so the quota provider can keep polling) and the DHCP broadcast.
#
# Why packet level: a score cap only steers the orchestrator. The kernel
# still holds the backup default route, and when the primary loses carrier
# the kernel falls back to it on its own — no failover decision involved.
# Only a firewall rule stops that traffic.
#
# State = existence of ${QUOTA_HARD_BLOCK_STATE_DIR}/quota-block.nft. The file
# is a regular, self-contained nftables script (it flushes its own table
# first, so re-applying never duplicates rules). Add
#     include "/var/lib/linux-dual-wan-failover-quota-block/*.nft"
# to /etc/nftables.conf and the block survives reboot and ruleset reloads;
# without the include, this script re-applies it on its next run.
#
# Decision per run:
#   limit_pct >= QUOTA_HARD_BLOCK_PCT                  → block
#   limit_pct <  threshold, snapshot fresh, new cycle  → lift
#   snapshot missing / unreadable / stale              → keep state (fail-closed)
# "New cycle" = limit_pct > 0, or billing_cycle_days_left went up since the
# last run, or the provider does not report billing_cycle_days_left at all.
# The second criterion matters because the block itself drops the traffic
# that would otherwise lift the counter above 0 after a reset.
#
# failover-monitor, nmcli-failover-monitor and the web UI read the same state
# file; none of them evaluates a threshold of its own.
#
# Designed to be invoked by quota-hard-block.timer (root: nft needs
# CAP_NET_ADMIN).

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
readonly SCRIPT_DIR
LIB_DIR="${LIB_DIR:-${SCRIPT_DIR}/../lib}"

# Overridable for tests; not readonly on purpose.
FAILOVER_CONF="${FAILOVER_CONF:-/etc/linux-dual-wan-failover/failover.conf}"
NFT_BIN="${NFT_BIN:-nft}"

if [[ -f "$FAILOVER_CONF" ]]; then
    # shellcheck disable=SC1090
    source "$FAILOVER_CONF"
fi

# shellcheck source=../lib/common.sh
source "${LIB_DIR}/common.sh" || {
    echo "FATAL: failed to source common.sh from ${LIB_DIR}" >&2
    exit 1
}

QUOTA_HARD_BLOCK="${QUOTA_HARD_BLOCK:-false}"
QUOTA_HARD_BLOCK_PCT="${QUOTA_HARD_BLOCK_PCT:-99}"
QUOTA_HARD_BLOCK_ALLOW="${QUOTA_HARD_BLOCK_ALLOW:-}"
QUOTA_HARD_BLOCK_STATE_DIR="${QUOTA_HARD_BLOCK_STATE_DIR:-/var/lib/linux-dual-wan-failover-quota-block}"
QUOTA_PROVIDER="${QUOTA_PROVIDER:-none}"
QUOTA_SNAPSHOT_PATH="${QUOTA_SNAPSHOT_PATH:-/var/lib/linux-dual-wan-failover/quota-snapshot.json}"
QUOTA_SNAPSHOT_MAX_STALE_SEC="${QUOTA_SNAPSHOT_MAX_STALE_SEC:-3600}"
BACKUP_IFACE="${BACKUP_IFACE:-lte0}"

readonly NFT_TABLE="ldwf_quota_block"
BLOCK_FILE="${QUOTA_HARD_BLOCK_STATE_DIR}/quota-block.nft"
DAYS_LEFT_FILE="${QUOTA_HARD_BLOCK_STATE_DIR}/last_days_left"

threshold() {
    if [[ "$QUOTA_HARD_BLOCK_PCT" =~ ^[0-9]+$ ]] \
        && [[ "$QUOTA_HARD_BLOCK_PCT" -ge 1 ]] \
        && [[ "$QUOTA_HARD_BLOCK_PCT" -le 100 ]]; then
        echo "$QUOTA_HARD_BLOCK_PCT"
    else
        # >&2: called inside $(...); the toolkit logger may write to stdout
        log "WARNING" "QUOTA_HARD_BLOCK_PCT='${QUOTA_HARD_BLOCK_PCT}' invalid (integer 1-100), using 99" >&2
        echo 99
    fi
}

# Everything that ends up inside the nftables script is validated first —
# the file is loaded as root.
validate_inputs() {
    if [[ ! "$BACKUP_IFACE" =~ ^[A-Za-z0-9_.:-]{1,15}$ ]]; then
        log "ERROR" "BACKUP_IFACE='${BACKUP_IFACE}' is not a valid interface name"
        return 1
    fi
    local entry
    for entry in $QUOTA_HARD_BLOCK_ALLOW; do
        if [[ ! "$entry" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}(/[0-9]{1,2})?$ ]]; then
            log "ERROR" "QUOTA_HARD_BLOCK_ALLOW entry '${entry}' is not an IPv4 address or CIDR"
            return 1
        fi
    done
    return 0
}

render_rules() {
    local allow="255.255.255.255" entry
    for entry in $QUOTA_HARD_BLOCK_ALLOW; do
        allow+=", ${entry}"
    done
    cat <<EOF
# Generated by quota-hard-block.sh — do not edit; the next run overwrites it.
# Drops all traffic leaving via ${BACKUP_IFACE} except to: ${allow}
table inet ${NFT_TABLE} {}
flush table inet ${NFT_TABLE}

table inet ${NFT_TABLE} {
    chain block_output {
        type filter hook output priority 0; policy accept;
        oifname "${BACKUP_IFACE}" ip daddr != { ${allow} } counter drop
        oifname "${BACKUP_IFACE}" meta nfproto ipv6 counter drop
    }

    chain block_forward {
        type filter hook forward priority -10; policy accept;
        oifname "${BACKUP_IFACE}" counter drop
    }
}
EOF
}

table_present() {
    "$NFT_BIN" list table inet "$NFT_TABLE" >/dev/null 2>&1
}

# Returns 0 = newly blocked, 1 = already blocked, 2 = error.
apply_block() {
    local was_blocked=1 changed=1 tmp
    [[ -f "$BLOCK_FILE" ]] && was_blocked=0

    validate_inputs || return 2
    install -d -m 0755 "$QUOTA_HARD_BLOCK_STATE_DIR" || return 2
    tmp="$(mktemp "${BLOCK_FILE}.XXXXXX")" || return 2
    render_rules > "$tmp"
    if cmp -s "$tmp" "$BLOCK_FILE"; then
        rm -f "$tmp"
    else
        chmod 0644 "$tmp" && mv "$tmp" "$BLOCK_FILE" || { rm -f "$tmp"; return 2; }
        changed=0
    fi

    if [[ $changed -eq 0 ]] || ! table_present; then
        if ! "$NFT_BIN" -f "$BLOCK_FILE"; then
            log "ERROR" "nft -f ${BLOCK_FILE} failed — backup link is NOT blocked"
            return 2
        fi
        log "INFO" "nftables table inet ${NFT_TABLE} loaded"
    fi
    [[ $was_blocked -eq 0 ]] && return 1
    return 0
}

# Returns 0 if a block was lifted, 1 if there was none.
lift_block() {
    local had_block=1
    if [[ -f "$BLOCK_FILE" ]]; then
        rm -f "$BLOCK_FILE"
        had_block=0
    fi
    if table_present; then
        "$NFT_BIN" delete table inet "$NFT_TABLE" \
            || log "WARNING" "nft delete table inet ${NFT_TABLE} failed"
        had_block=0
    fi
    return $had_block
}

# Keeps an existing block in place when the table vanished (e.g. after a
# ruleset reload without the include line).
reconcile() {
    if [[ -f "$BLOCK_FILE" ]] && ! table_present; then
        apply_block >/dev/null
    fi
    return 0
}

# Prints "<limit_pct>|<days_left or empty>" or nothing if unusable.
read_snapshot() {
    [[ -f "$QUOTA_SNAPSHOT_PATH" ]] || return 0
    python3 - "$QUOTA_SNAPSHOT_PATH" <<'PYEOF' 2>/dev/null
import json, sys
try:
    with open(sys.argv[1]) as f:
        d = json.load(f)
    pct = d.get("limit_pct")
    if pct is None or isinstance(pct, bool):
        sys.exit(0)
    days = d.get("billing_cycle_days_left")
    days = "" if days is None or isinstance(days, bool) else str(int(days))
    print(f"{float(pct):.2f}|{days}")
except (OSError, ValueError, TypeError, json.JSONDecodeError):
    sys.exit(0)
PYEOF
}

snapshot_fresh() {
    local mtime now
    mtime=$(stat -c %Y "$QUOTA_SNAPSHOT_PATH" 2>/dev/null || echo 0)
    now=$(date +%s)
    [[ $((now - mtime)) -le $QUOTA_SNAPSHOT_MAX_STALE_SEC ]]
}

# A reading below the threshold only lifts the block when it plausibly comes
# from a new cycle: counter above 0, days-left went up, or the provider does
# not report days-left (then a fresh reading is all there is to go on).
# Guards against a modem glitch reporting 0 mid-cycle.
new_cycle_confirmed() {
    local pct="$1" days_left="$2" new_cycle="$3"
    awk -v p="$pct" 'BEGIN { exit !(p > 0) }' && return 0
    [[ "$new_cycle" == "true" ]] && return 0
    [[ -z "$days_left" ]]
}

main() {
    if [[ "$QUOTA_HARD_BLOCK" != "true" || "$QUOTA_PROVIDER" == "none" ]]; then
        if lift_block; then
            send_notification "Quota hard block lifted: disabled in config (QUOTA_HARD_BLOCK=${QUOTA_HARD_BLOCK}, QUOTA_PROVIDER=${QUOTA_PROVIDER})." "info" || true
        fi
        return 0
    fi

    local thr snapshot pct days_left last_days_left="" fresh=false
    thr=$(threshold)
    snapshot=$(read_snapshot)
    [[ -f "$DAYS_LEFT_FILE" ]] && last_days_left=$(cat "$DAYS_LEFT_FILE" 2>/dev/null)

    if [[ -z "$snapshot" ]]; then
        log "WARNING" "quota snapshot ${QUOTA_SNAPSHOT_PATH} missing, unreadable or limit_pct=null — block state unchanged"
        reconcile
        return 0
    fi
    IFS='|' read -r pct days_left <<< "$snapshot"
    snapshot_fresh && fresh=true

    local over=false new_cycle=false
    awk -v p="$pct" -v t="$thr" 'BEGIN { exit !(p >= t) }' && over=true
    if [[ "$days_left" =~ ^[0-9]+$ && "$last_days_left" =~ ^[0-9]+$ ]] \
        && [[ "$days_left" -gt "$last_days_left" ]]; then
        new_cycle=true
    fi

    if [[ "$over" == "true" ]]; then
        local rc
        apply_block; rc=$?
        case "$rc" in
            0)
                send_notification "Quota hard block ACTIVE: ${pct}% of the backup-link quota used (threshold ${thr}%). All traffic via ${BACKUP_IFACE} is dropped, even if the primary fails." "critical" || true
                ;;
            2)
                send_notification "Quota hard block could NOT be applied (${pct}% >= ${thr}%). Check: journalctl -u quota-hard-block.service" "critical" || true
                ;;
        esac
        if [[ "$new_cycle" == "true" && "$fresh" == "true" ]]; then
            send_notification "New billing cycle detected (days left ${last_days_left} -> ${days_left}), but the quota still reads ${pct}%. Block stays active — check the provider's counter." "warning" || true
        fi
    elif [[ "$fresh" == "true" ]] && new_cycle_confirmed "$pct" "$days_left" "$new_cycle"; then
        if lift_block; then
            send_notification "Quota hard block lifted: ${pct}% used (threshold ${thr}%). Failover to ${BACKUP_IFACE} is possible again." "info" || true
        fi
    else
        log "INFO" "quota ${pct}% (fresh=${fresh}) — no lift without a fresh reading from a new cycle"
        reconcile
    fi

    if [[ "$fresh" == "true" && "$days_left" =~ ^[0-9]+$ ]]; then
        install -d -m 0755 "$QUOTA_HARD_BLOCK_STATE_DIR" && echo "$days_left" > "$DAYS_LEFT_FILE"
    fi
    return 0
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
